apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xelta-app-ingress
  namespace: default # Change to your app's namespace
  annotations:
    # --- CRITICAL FOR SECURITY & AUTOMATION ---
    # Get these values from the `terraform output` command after you apply the infrastructure.
    # Example: terraform output waf_arn
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:ap-south-1:123456789012:regional/webacl/xelta-dev-waf/..." # <-- Get this ARN from Terraform output

    # Example: terraform output alb_security_group_id
    alb.ingress.kubernetes.io/security-groups: "sg-0123456789abcdef0" # <-- Get this SG ID from Terraform output

    # --- Standard ALB Configuration ---
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service # Your app's Kubernetes service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service # Your backend k8s service
            port:
              number: 8080