name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod

jobs:
  deploy-dev:
    name: 'Deploy Dev Environment'
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./terraform/live

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        run: terraform init

      - name: Select Dev Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Plan
        run: terraform plan -no-color -var-file="env_vars/dev.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color -var-file="env_vars/dev.tfvars"

  deploy-prod:
    name: 'Deploy Prod Environment'
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./terraform/live

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_PROD }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        run: terraform init

      - name: Select Prod Workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Terraform Plan
        run: terraform plan -no-color -var-file="env_vars/prod.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color -var-file="env_vars/prod.tfvars"